name: "Deploiement CI/CD"

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:

# Deploiement du frontend

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Check code quality with ESLint
        run: npm run lint
        continue-on-error: false

      - name: Run unit tests
        run: npm run test --if-present

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./frontend
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

# Deploiement du backend

  deploy-backend:
      name: Deploy Backend
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./backend

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci

        - name: Run unit tests
          run: npm test --if-present

        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-args: '--prod'
            working-directory: ./backend
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}